In [3]:
import numpy as np
a =np.array((1,2,3,4,5))
a

array([1, 2, 3, 4, 5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a.shape


(5,)

In [6]:
a.ndim

1

In [7]:
a.size

5

In [9]:
b = np.array([1,2,3,4,5,6,7,8,9])
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b.sum()

45

In [26]:
a.dtype

dtype('int32')

In [13]:
a.dtype

dtype('int32')

In [15]:
a.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [19]:
c= a.sum()
d =b.sum()
e =c+d
e

60

In [20]:
lst = [[0,1,2,3,4], [5,6,7,8,9]]
lst

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [22]:
y = np.array(lst)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
y.dtype

dtype('int32')

In [24]:
y.shape

(2, 5)

In [27]:
y.ndim

2

In [28]:
y.size

10

In [29]:
x = y+a
x

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14]])

In [30]:
a

array([1, 2, 3, 4, 5])

In [40]:
f =np.array([1,2,3,4,5])
f

array([1, 2, 3, 4, 5])

In [41]:
t = y +f
t

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14]])

In [42]:
y.shape


(2, 5)

In [43]:
y.dtype

dtype('int32')

In [44]:
y.astype(np.float32)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)

In [45]:
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
y[0]

array([0, 1, 2, 3, 4])

In [47]:
y[1]

array([5, 6, 7, 8, 9])

In [51]:
p= y[1]+ y[0]
p

array([ 5,  7,  9, 11, 13])

In [52]:
p[2:]

array([ 9, 11, 13])

In [53]:
y[-1:]

array([[5, 6, 7, 8, 9]])

In [54]:
y[4:]

array([], shape=(0, 5), dtype=int32)

In [55]:
p[4:]

array([13])

In [56]:
p[::2]

array([ 5,  9, 13])

In [57]:
st = np.array(['ali', 'reza', 'mohamad'])
st

array(['ali', 'reza', 'mohamad'], dtype='<U7')

In [58]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [59]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = arr1.copy()
arr1[0] = 7

In [60]:
arr1

array([7, 2, 3, 4, 5, 6])

In [61]:
arr2

array([1, 2, 3, 4, 5, 6])

In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [63]:
arr2.shape

(6,)

In [65]:
arr2.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


In [70]:
arr4 = np.array([1,2,3])
arr5 = np.array([4,5,6])
resultvstack = np.vstack((arr4, arr5))
resultvstack

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [72]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [73]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [74]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [75]:
arr =np.array([5,8,7,6,2,10,0,45,78,2,4,1,2])
arr2 =np.sort(arr)
arr2

array([ 0,  1,  2,  2,  2,  4,  5,  6,  7,  8, 10, 45, 78])

In [76]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [77]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]
